### ISSUE TITLE
SoapFault ao tentar calcular frete

### ISSUE THREAD

**Issue by bruno-rodrigues** [FrenetGatewaydeFretes/woo-shipping-gateway#1]
Olá, 
O webservice da frenet está disparando uma exceção [bem aqui](https://github.com/FrenetGatewaydeFretes/woo-shipping-gateway/blob/master/includes/class-wc-frenet.php#L638). Coloquei essa linha dentro de um try..catch e a mensagem de erro é:

`Server was unable to read request. ---> There is an error in XML document (2, 522). ---> Input string was not in a correct format.`

Ainda não sei se existe alguma ligação lógica, mas **o erro acontece quando eu adiciono um item ao carrinho, nenhum usuário está logado e eu preencho o cálculo de frente (com um frete válido)**. Se eu:

1. Esvaziar o carrinho
2. Fazer login (com qualquer usuário)
3. Adicionar o produto ao carrinho
4. Acessar a página do carrinho

Tudo volta ao normal. Alguma idéia do que posso estar fazendo errado?

**Comment by rafaelmancini** [comment]
Bruno,
Este erro pode estar sendo causado por alguma configuração errada em seu módulo. Verifique os dados de chave de acesso, senha e token. Outro detalhe pode ser o preenchimento do CEP. O usuário logado já terá este campo preenchido, um "não logado" não terá este campo, então deve obrigá-lo a preencher, caso contrário o plugin dispara a exception.
Abra por favor um ticket na Central de Ajuda https://frenet.zendesk.com/ que o pessoal irá lhe auxiliar.
Abs
