### ISSUE TITLE
Quantity agora é obrigatório?

### ISSUE THREAD

**Issue by bruno-rodrigues** [FrenetGatewaydeFretes/woo-shipping-gateway#2]
Boa tarde,

Na noite de ontem comecei a receber um erro na chamada SOAP:

`[PHP Fatal error:  SOAP-ERROR: Encoding: object has no 'Quantity' property in [ ...]/class-wc-frenet.php on line 687`

Pelo que eu entendi, a estrutura de `ShippingItem` agora exige o campo Quantity, como visto aqui:
[http://services.frenet.com.br/logistics/ShippingQuoteWS.asmx?WSDL](http://services.frenet.com.br/logistics/ShippingQuoteWS.asmx?WSDL)

```
    <s:complexType name="ShippingItem">
        <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="Weight" type="s:decimal"/>
            <s:element minOccurs="1" maxOccurs="1" name="Length" type="s:decimal"/>
            <s:element minOccurs="1" maxOccurs="1" name="Height" type="s:decimal"/>
            <s:element minOccurs="1" maxOccurs="1" name="Width" type="s:decimal"/>
            <s:element minOccurs="1" maxOccurs="1" name="Diameter" type="s:decimal"/>
            <s:element minOccurs="0" maxOccurs="1" name="SKU" type="s:string"/>
            <s:element minOccurs="0" maxOccurs="1" name="Category" type="s:string"/>
            <s:element minOccurs="1" maxOccurs="1" name="isFragile" type="s:boolean"/>
            <s:element minOccurs="1" maxOccurs="1" name="Quantity" type="s:int"/>
        </s:sequence>
    </s:complexType>
```
Mas a tabela apresentada na sua documenta não explicita a necessidade do campo `Quantity`: 
![screen shot 2017-02-12 at 2 18 51 pm](https://cloud.githubusercontent.com/assets/7862345/22863876/d29e167a-f12e-11e6-81cb-e9fefbb242df.png)

Para resolver o problema, tive que adicionar a linha `$shippingItem->Quantity = $qty;` logo após 

```
$shippingItem->Weight   = $_weight;
$shippingItem->Length   = $_length;
$shippingItem->Height   = $_height;
$shippingItem->Width    = $_width;
$shippingItem->Diameter = 0;
$shippingItem->SKU      = $product->get_sku();
```

nas funções `frenet_calculate` e `frenet_calculate_json`.

Estou correto ou não mudou nada no seu webservice?

**Comment by rafaelmancini** [comment]
Olá Bruno,
Foi criada esta nova propriedade, mas já corrigimos para ficar não obrigatória.
