### ISSUE TITLE
This plugin has not been tested with your current version of WordPress (4.5.2)

### ISSUE THREAD

**Issue by miabianca** [FrenetGatewaydeFretes/woo-shipping-gateway#8]
Can someone help? I can't contact the Freenet Support. It says it is not compatible with Woocommerce. We can't proceed to payment: https://www.evolutionathletic.com.au/

https://prnt.sc/uvvyzv

Thank you in advance.

**Comment by rafaelmancini** [comment]
Hello Mia, you could contact us by email suporte@frenet.com.br.
We have tested this plugin until the last version of Wordpress (5.5.1) and Woocomerce (4.5.2)
You could see at: https://woocommerce40.lithiumsoftware.com.br/?product=variable-product-1

We have a help page (Pt-BR) that show how configure the plugin: https://ajuda.frenet.com.br/s/article/2090941-configuracao-plugin-frenet-woocommerce
Be sure that your token is correct.
